version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: places-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - places-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: places-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - places-network
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: places-api-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: places
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - places-network

networks:
  places-network:
    driver: bridge

volumes:
  dbdata:
